### ISSUE TITLE
Extract pdm-plugin-torch?

### ISSUE THREAD

**Issue by dsully** [EmbarkStudios/pdm-plugin-torch#6]
Hi - I have need of `pdm-plugin-torch` in another project. Any chance it could be extracted into it's own repository and published to pypi?

Thanks!

**Comment by tgolsson** [comment]
@dsully The plugin is on PyPi and open here now.

**Comment by dsully** [comment]
Fantastic! I'll be able to test in the next few days. Thank you.

**Comment by tgolsson** [comment]
Closing this as the move has been completed. Feel free to open new issues if you run into other problems :-)

**Comment by frostming** [comment]
@tgolsson You may want to try the latest beta release 2.5.0b0 published just now because there are some refactor around the PDM sources.

**Comment by tgolsson** [comment]
@frostming Thanks for the heads up!
